directory: ~/music/beetsdir
library: ~/.beets.db

plugins:
    missing duplicates fetchart embedart zero convert chroma info play discogs random fuzzy

import:
    copy: yes
    log: ~/.beetsimports.log

fuzzy:
    threshold: 0.8
    prefix: "?"

fetchart:
    enforce_ratio: no
    minwidth: 500

zero:
    fields: albumartist_sort artist_sort comments genre
    update_database: true

convert:
    dest: /tmp/
    never_convert_lossy_files: yes
    formats:
        ipod:
            command: ffmpeg -v warning -analyzeduration 100000000 -i $source -vn -c:a alac -ar 48000 -sample_fmt s16p $dest
            extension: m4a
        opus: ffmpeg -i $source -y -vn -acodec libopus -ab 128k $dest
        aac:
            extension: m4a
            command: ffmpeg -i $source -vn -c:a libfdk_aac -vbr 5 $dest
        mp3: ffmpeg -i $source -y -vn -c:a libmp3lame $dest

play:
    warning_threshold: no
    raw: yes
    command: ds vlc --one-instance --playlist-enqueue --started-from-file -ZL
