directory: ~/music/beetsdir
library: ~/music/beetslibrary.blb

plugins:
    missing duplicates fetchart embedart zero convert chroma info smartplaylist play check

import:
    copy: yes
    log: ~/music/beetsimports.log

fetchart:
    enforce_ratio: yes
    minwidth: 200

zero:
    fields: albumartist_sort artist_sort comments genre
    update_database: true

convert:
    dest: "/common/itunesMedia/Automatically Add to iTunes"
    never_convert_lossy_files: yes
    format: ipod
    formats:
        ipod:
            command: avconv -v warning -analyzeduration 100000000 -i $source -vn -c:a alac -ar 48000 -sample_fmt s16p $dest
            extension: m4a

smartplaylist:
    playlist_dir: ~/music/playlists
    playlists:
        - name: bigmany.m3u
          query: ['albumartist:"Dire Straits"', 'albumartist:"Mark Knopfler"', 'albumartist:"Pink Floyd"']

play:
    command: ds vlc --one-instance --no-playlist-enqueue --started-from-file -ZL
