directory: ~/music/beetsdir
library: ~/.beets.db
asciify_path: yes

plugins:
    missing duplicates fetchart embedart zero convert chroma info smartplaylist play discogs

import:
    copy: yes
    log: ~/.beetsimports.log

fetchart:
    enforce_ratio: no
    minwidth: 500

zero:
    fields: albumartist_sort artist_sort comments genre
    update_database: true

convert:
    dest: "/home/nathdwek/multiM/music/converted"
    never_convert_lossy_files: yes
    format: mp320
    formats:
        ipod:
            command: avconv -v warning -analyzeduration 100000000 -i $source -vn -c:a alac -ar 48000 -sample_fmt s16p $dest
            extension: m4a

smartplaylist:
    playlist_dir: ~/music/playlists
    playlists:
        - name: bigmany.m3u
          query: ['albumartist:"Dire Straits"', 'albumartist:"Mark Knopfler"', 'albumartist:"Pink Floyd"']

play:
    warning_threshold: no
    raw: yes
    command: ds vlc --one-instance --playlist-enqueue --started-from-file -ZL
